name: iOS CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  ios:
    runs-on: macos-14
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.2.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          curl --output ../hxcpp-4.3.45.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.45/hxcpp-4.3.45.zip
          haxelib install ../hxcpp-4.3.45.zip --quiet
          haxelib dev extension-webm $GITHUB_WORKSPACE

      - name: Rebuild Lime tools
        run: |
          haxelib run lime setup -alias -y

      - name: Rebuild Extension-WebM (iOS)
        run: |
          rm -rf ./ndll
          mkdir ./ndll
          lime rebuild extension-webm ios

      - uses: actions/upload-artifact@v4
        with:
          name: iPhone-NDLL
          path: ndll
          if-no-files-found: error
